browser chrome
url https://dev.octopussaas.com/
username henry@test.com
password Nayan123!@




browz- chrome , firefox , edge .

development:
https://dev.octopussaas.com/ 
user-henry@test.com
pwd-Nayan123!@



Staging:
https://staging.octopussaas.com/
user-priyamv@pravaahconsulting.com
pwd-12345678



production:
https://app.octopussaas.com/auth
user-felix@mailtest.com
pwd-Felix@08